from .errors import (
    ArtistError,
    BaseClientError,
    CaptchaException,
    LoginError,
    ParentException,
    PlaylistError,
    RequestError,
    SaverError,
    SolverError,
    SongError,
    UserError,
    GeneratorError,
    PasswordError,
)
